"""initial authoritative foundation

Revision ID: d3f5ba5f0d58
Revises:
Create Date: 2026-09-08 01:59:34.039973
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "d3f5ba5f0d58"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crew_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_crew_groups_name")),
    )
    op.create_table(
        "login_throttles",
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key_hash", name=op.f("pk_login_throttles")),
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.Column("decline_policy", sa.String(length=32), nullable=False),
        sa.Column("lead_minutes_race_day", sa.Integer(), nullable=False),
        sa.Column("statutory_holiday_region", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("name", name=op.f("uq_regions_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("credential_hash", sa.String(length=512), nullable=False),
        sa.Column("credential_kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("theme", sa.String(length=24), nullable=False),
        sa.Column("auth_epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_audit_events_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False)
    op.create_index(op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False)
    op.create_table(
        "base_positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("crew_group_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["crew_group_id"], ["crew_groups.id"], name=op.f("fk_base_positions_crew_group_id_crew_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_base_positions")),
        sa.UniqueConstraint("crew_group_id", "name", name=op.f("uq_base_positions_crew_group_id")),
    )
    op.create_index(
        op.f("ix_base_positions_crew_group_id"), "base_positions", ["crew_group_id"], unique=False
    )
    op.create_index(op.f("ix_base_positions_name"), "base_positions", ["name"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("roster_changes", sa.Boolean(), nullable=False),
        sa.Column("night_before", sa.Boolean(), nullable=False),
        sa.Column("two_days_before", sa.Boolean(), nullable=False),
        sa.Column("one_hour_before", sa.Boolean(), nullable=False),
        sa.Column("open_positions", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_notification_preferences")),
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], name=op.f("fk_operations_region_id_regions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
    )
    op.create_index(op.f("ix_operations_region_id"), "operations", ["region_id"], unique=False)
    op.create_table(
        "passkey_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", sa.String(length=200), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_passkey_credentials_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passkey_credentials")),
        sa.UniqueConstraint("credential_id", name=op.f("uq_passkey_credentials_credential_id")),
    )
    op.create_index(op.f("ix_passkey_credentials_user_id"), "passkey_credentials", ["user_id"], unique=False)
    op.create_table(
        "people",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("home_region_id", sa.Uuid(), nullable=True),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["home_region_id"], ["regions.id"], name=op.f("fk_people_home_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    op.create_index(op.f("ix_people_display_name"), "people", ["display_name"], unique=False)
    op.create_index(op.f("ix_people_home_region_id"), "people", ["home_region_id"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_hash", sa.String(length=64), nullable=False),
        sa.Column("encrypted_subscription", sa.JSON(), nullable=False),
        sa.Column("device_label", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_push_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint_hash", name=op.f("uq_push_subscriptions_endpoint_hash")),
    )
    op.create_index(op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False)
    op.create_table(
        "role_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(role = 'ADMIN' AND region_id IS NULL) OR role <> 'ADMIN'",
            name=op.f("ck_role_grants_admin_global_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"], ["users.id"], name=op.f("fk_role_grants_granted_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], name=op.f("fk_role_grants_region_id_regions")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_role_grants_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_grants")),
    )
    op.create_index(op.f("ix_role_grants_region_id"), "role_grants", ["region_id"], unique=False)
    op.create_index(op.f("ix_role_grants_user_id"), "role_grants", ["user_id"], unique=False)
    op.create_index(
        "ix_role_grants_user_region_role", "role_grants", ["user_id", "region_id", "role"], unique=False
    )
    op.create_index(
        "uq_role_grants_global",
        "role_grants",
        ["user_id", "role"],
        unique=True,
        postgresql_where=sa.text("region_id IS NULL"),
    )
    op.create_index(
        "uq_role_grants_regional",
        "role_grants",
        ["user_id", "role", "region_id"],
        unique=True,
        postgresql_where=sa.text("region_id IS NOT NULL"),
    )
    op.create_table(
        "signup_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("requested_region_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_region_id"],
            ["regions.id"],
            name=op.f("fk_signup_requests_requested_region_id_regions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signup_requests")),
    )
    op.create_index(op.f("ix_signup_requests_email"), "signup_requests", ["email"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("display_colour", sa.String(length=7), nullable=False),
        sa.Column("map_reference", sa.String(length=500), nullable=True),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(display_colour) = 7 AND substr(display_colour, 1, 1) = '#'",
            name=op.f("ck_tracks_valid_hex_colour"),
        ),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], name=op.f("fk_tracks_region_id_regions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracks")),
        sa.UniqueConstraint("region_id", "name", name=op.f("uq_tracks_region_id")),
    )
    op.create_index(op.f("ix_tracks_region_id"), "tracks", ["region_id"], unique=False)
    op.create_table(
        "trusted_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("auth_epoch", sa.Integer(), nullable=False),
        sa.Column("elevated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trusted_devices_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trusted_devices")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_trusted_devices_token_hash")),
    )
    op.create_index(op.f("ix_trusted_devices_expires_at"), "trusted_devices", ["expires_at"], unique=False)
    op.create_index(op.f("ix_trusted_devices_user_id"), "trusted_devices", ["user_id"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("home_region_id", sa.Uuid(), nullable=True),
        sa.Column("fuel_type", sa.String(length=40), nullable=True),
        sa.Column("lifecycle", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["home_region_id"], ["regions.id"], name=op.f("fk_vehicles_home_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("name", name=op.f("uq_vehicles_name")),
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activated_user_id"], ["users.id"], name=op.f("fk_invitations_activated_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], name=op.f("fk_invitations_created_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], name=op.f("fk_invitations_person_id_people")),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], name=op.f("fk_invitations_region_id_regions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(op.f("ix_invitations_email"), "invitations", ["email"], unique=False)
    op.create_table(
        "person_crew_groups",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("crew_group_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crew_group_id"],
            ["crew_groups.id"],
            name=op.f("fk_person_crew_groups_crew_group_id_crew_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_person_crew_groups_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "crew_group_id", name=op.f("pk_person_crew_groups")),
    )
    op.create_table(
        "travel_legs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("travel_date", sa.Date(), nullable=False),
        sa.Column("origin", sa.String(length=160), nullable=False),
        sa.Column("destination", sa.String(length=160), nullable=False),
        sa.Column("starts_at", sa.Time(), nullable=True),
        sa.Column("ends_at", sa.Time(), nullable=True),
        sa.Column("vehicle_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_travel_legs_operation_id_operations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"], ["vehicles.id"], name=op.f("fk_travel_legs_vehicle_id_vehicles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_travel_legs")),
    )
    op.create_index(op.f("ix_travel_legs_operation_id"), "travel_legs", ["operation_id"], unique=False)
    op.create_table(
        "user_person_links",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_user_person_links_person_id_people")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_person_links_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_person_links")),
    )
    op.create_index(op.f("ix_user_person_links_person_id"), "user_person_links", ["person_id"], unique=True)
    op.create_table(
        "workdays",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("current_published_revision_id", sa.Uuid(), nullable=True),
        sa.Column("current_draft_revision_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], name=op.f("fk_workdays_created_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["operations.id"], name=op.f("fk_workdays_operation_id_operations")
        ),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], name=op.f("fk_workdays_region_id_regions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workdays")),
    )
    op.create_index(op.f("ix_workdays_region_id"), "workdays", ["region_id"], unique=False)
    op.create_table(
        "workday_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workday_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("based_on_revision_id", sa.Uuid(), nullable=True),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=True),
        sa.Column("track_name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("track_colour_snapshot", sa.String(length=7), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("on_track_time", sa.Time(), nullable=True),
        sa.Column("first_trial_time", sa.Time(), nullable=True),
        sa.Column("first_race_time", sa.Time(), nullable=True),
        sa.Column("last_race_time", sa.Time(), nullable=True),
        sa.Column("race_count", sa.Integer(), nullable=True),
        sa.Column("day_note", sa.Text(), nullable=False),
        sa.Column("change_reason", sa.String(length=500), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["based_on_revision_id"],
            ["workday_revisions.id"],
            name=op.f("fk_workday_revisions_based_on_revision_id_workday_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], name=op.f("fk_workday_revisions_created_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_workday_revisions_published_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_workday_revisions_track_id_tracks")
        ),
        sa.ForeignKeyConstraint(
            ["workday_id"],
            ["workdays.id"],
            name=op.f("fk_workday_revisions_workday_id_workdays"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workday_revisions")),
        sa.UniqueConstraint("workday_id", "revision_number", name=op.f("uq_workday_revisions_workday_id")),
    )
    op.create_index(op.f("ix_workday_revisions_work_date"), "workday_revisions", ["work_date"], unique=False)
    op.create_index(
        op.f("ix_workday_revisions_workday_id"), "workday_revisions", ["workday_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_workdays_current_draft_revision_id_workday_revisions"),
        "workdays",
        "workday_revisions",
        ["current_draft_revision_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_workdays_current_published_revision_id_workday_revisions"),
        "workdays",
        "workday_revisions",
        ["current_published_revision_id"],
        ["id"],
    )
    op.create_table(
        "allowance_indicators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("entitlement_hours", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("explanation", sa.String(length=240), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_allowance_indicators_person_id_people")
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["workday_revisions.id"],
            name=op.f("fk_allowance_indicators_revision_id_workday_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allowance_indicators")),
    )
    op.create_index(
        op.f("ix_allowance_indicators_person_id"), "allowance_indicators", ["person_id"], unique=False
    )
    op.create_index(
        op.f("ix_allowance_indicators_revision_id"), "allowance_indicators", ["revision_id"], unique=False
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("slot_key", sa.Uuid(), nullable=False),
        sa.Column("base_position_id", sa.Uuid(), nullable=True),
        sa.Column("slot_index", sa.Integer(), nullable=True),
        sa.Column("display_name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("person_name_snapshot", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("note_private", sa.Boolean(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=True),
        sa.Column("vehicle_name_snapshot", sa.String(length=120), nullable=True),
        sa.Column("accommodation_name", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_position_id"],
            ["base_positions.id"],
            name=op.f("fk_assignments_base_position_id_base_positions"),
        ),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], name=op.f("fk_assignments_person_id_people")),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["workday_revisions.id"],
            name=op.f("fk_assignments_revision_id_workday_revisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"], ["vehicles.id"], name=op.f("fk_assignments_vehicle_id_vehicles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
        sa.UniqueConstraint("revision_id", "slot_key", name=op.f("uq_assignments_revision_id")),
    )
    op.create_index(op.f("ix_assignments_person_id"), "assignments", ["person_id"], unique=False)
    op.create_index(op.f("ix_assignments_revision_id"), "assignments", ["revision_id"], unique=False)
    op.create_table(
        "human_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workday_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_human_changes_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["workday_revisions.id"],
            name=op.f("fk_human_changes_revision_id_workday_revisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workday_id"],
            ["workdays.id"],
            name=op.f("fk_human_changes_workday_id_workdays"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_changes")),
    )
    op.create_index(op.f("ix_human_changes_workday_id"), "human_changes", ["workday_id"], unique=False)
    op.create_table(
        "position_capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("base_position_id", sa.Uuid(), nullable=False),
        sa.Column("signal", sa.String(length=24), nullable=False),
        sa.Column("source_revision_id", sa.Uuid(), nullable=True),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_position_id"],
            ["base_positions.id"],
            name=op.f("fk_position_capabilities_base_position_id_base_positions"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_position_capabilities_changed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_position_capabilities_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_revision_id"],
            ["workday_revisions.id"],
            name=op.f("fk_position_capabilities_source_revision_id_workday_revisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_capabilities")),
        sa.UniqueConstraint(
            "person_id", "base_position_id", "signal", name=op.f("uq_position_capabilities_person_id")
        ),
    )
    op.create_index(
        op.f("ix_position_capabilities_base_position_id"),
        "position_capabilities",
        ["base_position_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_position_capabilities_person_id"), "position_capabilities", ["person_id"], unique=False
    )
    op.create_table(
        "programme_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("operational_time", sa.Time(), nullable=True),
        sa.Column("source_time", sa.Time(), nullable=True),
        sa.Column("source_provider", sa.String(length=80), nullable=True),
        sa.Column("source_retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manual_override", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["workday_revisions.id"],
            name=op.f("fk_programme_items_revision_id_workday_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programme_items")),
    )
    op.create_index(op.f("ix_programme_items_revision_id"), "programme_items", ["revision_id"], unique=False)
    now = datetime.now(UTC)
    region_table = sa.table(
        "regions",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("lifecycle", sa.String()),
        sa.column("decline_policy", sa.String()),
        sa.column("lead_minutes_race_day", sa.Integer()),
        sa.column("statutory_holiday_region", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        region_table,
        [
            {
                "id": uuid.UUID("10000000-0000-0000-0000-000000000001"),
                "name": "Northern",
                "lifecycle": "ACTIVE",
                "decline_policy": "MANAGER_REVIEW",
                "lead_minutes_race_day": 120,
                "statutory_holiday_region": None,
                "created_at": now,
            },
            {
                "id": uuid.UUID("10000000-0000-0000-0000-000000000002"),
                "name": "Central",
                "lifecycle": "ACTIVE",
                "decline_policy": "MANAGER_REVIEW",
                "lead_minutes_race_day": 120,
                "statutory_holiday_region": None,
                "created_at": now,
            },
            {
                "id": uuid.UUID("10000000-0000-0000-0000-000000000003"),
                "name": "Christchurch",
                "lifecycle": "ACTIVE",
                "decline_policy": "MANAGER_REVIEW",
                "lead_minutes_race_day": 120,
                "statutory_holiday_region": None,
                "created_at": now,
            },
            {
                "id": uuid.UUID("10000000-0000-0000-0000-000000000004"),
                "name": "Dunedin",
                "lifecycle": "ACTIVE",
                "decline_policy": "MANAGER_REVIEW",
                "lead_minutes_race_day": 120,
                "statutory_holiday_region": None,
                "created_at": now,
            },
            {
                "id": uuid.UUID("10000000-0000-0000-0000-000000000005"),
                "name": "Office",
                "lifecycle": "ACTIVE",
                "decline_policy": "MANAGER_REVIEW",
                "lead_minutes_race_day": 120,
                "statutory_holiday_region": None,
                "created_at": now,
            },
        ],
    )
    group_table = sa.table(
        "crew_groups",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("lifecycle", sa.String()),
    )
    op.bulk_insert(
        group_table,
        [
            {
                "id": uuid.UUID("20000000-0000-0000-0000-000000000001"),
                "name": "OB Crew",
                "lifecycle": "ACTIVE",
            },
            {
                "id": uuid.UUID("20000000-0000-0000-0000-000000000002"),
                "name": "Camera Crew",
                "lifecycle": "ACTIVE",
            },
            {
                "id": uuid.UUID("20000000-0000-0000-0000-000000000003"),
                "name": "Engineers",
                "lifecycle": "ACTIVE",
            },
            {
                "id": uuid.UUID("20000000-0000-0000-0000-000000000004"),
                "name": "Presenters",
                "lifecycle": "ACTIVE",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_programme_items_revision_id"), table_name="programme_items")
    op.drop_table("programme_items")
    op.drop_index(op.f("ix_position_capabilities_person_id"), table_name="position_capabilities")
    op.drop_index(op.f("ix_position_capabilities_base_position_id"), table_name="position_capabilities")
    op.drop_table("position_capabilities")
    op.drop_index(op.f("ix_human_changes_workday_id"), table_name="human_changes")
    op.drop_table("human_changes")
    op.drop_index(op.f("ix_assignments_revision_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_person_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_allowance_indicators_revision_id"), table_name="allowance_indicators")
    op.drop_index(op.f("ix_allowance_indicators_person_id"), table_name="allowance_indicators")
    op.drop_table("allowance_indicators")
    op.drop_constraint(
        op.f("fk_workdays_current_published_revision_id_workday_revisions"), "workdays", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_workdays_current_draft_revision_id_workday_revisions"), "workdays", type_="foreignkey"
    )
    op.drop_index(op.f("ix_workday_revisions_workday_id"), table_name="workday_revisions")
    op.drop_index(op.f("ix_workday_revisions_work_date"), table_name="workday_revisions")
    op.drop_table("workday_revisions")
    op.drop_index(op.f("ix_workdays_region_id"), table_name="workdays")
    op.drop_table("workdays")
    op.drop_index(op.f("ix_user_person_links_person_id"), table_name="user_person_links")
    op.drop_table("user_person_links")
    op.drop_index(op.f("ix_travel_legs_operation_id"), table_name="travel_legs")
    op.drop_table("travel_legs")
    op.drop_table("person_crew_groups")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_trusted_devices_user_id"), table_name="trusted_devices")
    op.drop_index(op.f("ix_trusted_devices_expires_at"), table_name="trusted_devices")
    op.drop_table("trusted_devices")
    op.drop_index(op.f("ix_tracks_region_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_signup_requests_email"), table_name="signup_requests")
    op.drop_table("signup_requests")
    op.drop_index("ix_role_grants_user_region_role", table_name="role_grants")
    op.drop_index("uq_role_grants_regional", table_name="role_grants")
    op.drop_index("uq_role_grants_global", table_name="role_grants")
    op.drop_index(op.f("ix_role_grants_user_id"), table_name="role_grants")
    op.drop_index(op.f("ix_role_grants_region_id"), table_name="role_grants")
    op.drop_table("role_grants")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_people_home_region_id"), table_name="people")
    op.drop_index(op.f("ix_people_display_name"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_passkey_credentials_user_id"), table_name="passkey_credentials")
    op.drop_table("passkey_credentials")
    op.drop_index(op.f("ix_operations_region_id"), table_name="operations")
    op.drop_table("operations")
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_base_positions_name"), table_name="base_positions")
    op.drop_index(op.f("ix_base_positions_crew_group_id"), table_name="base_positions")
    op.drop_table("base_positions")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("regions")
    op.drop_table("login_throttles")
    op.drop_table("crew_groups")
    # ### end Alembic commands ###
